using System;
using UnityEngine;

#if UNITY_EDITOR
using UnityEditor;
#endif

public enum OscillatorType
{
    Sine,
    Square,
    Saw,
    Triangle,
    Pwm,
    Noise
}

[Serializable]
public class OscillatorCurveSettings
{
    [Tooltip("Preset shape used to generate the curve.")]
    public OscillatorType oscillatorType = OscillatorType.Sine;

    [Tooltip("How many times the preset shape repeats per second.")]
    [Min(0.01f)]
    public float cyclesPerSecond = 1f;

    [Tooltip("Lowest value generated by the preset curve.")]
    [Range(0f, 1f)]
    public float minimumValue = 0f;

    [Tooltip("Highest value generated by the preset curve.")]
    [Range(0f, 1f)]
    public float maximumValue = 1f;

    [Tooltip("How much of each pulse stays on. Used by the PWM preset.")]
    [Range(0f, 1f)]
    public float pulseWidth = 0.5f;

    [Tooltip("How many points are used to draw the generated curve.")]
    [Range(16, 512)]
    public int curvePoints = 128;

    [Tooltip("Offset used by the smooth Noise preset.")]
    public int noiseSeed = 0;

    [Tooltip("Generated curve. You can edit this directly in the Inspector after choosing a preset.")]
    public AnimationCurve Curve = AnimationCurve.Linear(0f, 1f, 1f, 1f);

    public static OscillatorCurveSettings CreateDefaultAmplitude()
    {
        return new OscillatorCurveSettings
        {
            oscillatorType = OscillatorType.Pwm,
            cyclesPerSecond = 8f,
            minimumValue = 0f,
            maximumValue = 1f,
            pulseWidth = 0.2f,
            curvePoints = 128
        };
    }

    public static OscillatorCurveSettings CreateDefaultFrequency()
    {
        return new OscillatorCurveSettings
        {
            oscillatorType = OscillatorType.Sine,
            cyclesPerSecond = 1f,
            minimumValue = 0.4f,
            maximumValue = 1f,
            pulseWidth = 0.5f,
            curvePoints = 128
        };
    }

    public void Generate(float duration)
    {
        int keyCount = Mathf.Max(2, curvePoints);
        float safeDuration = Mathf.Max(0.01f, duration);
        float lowValue = Mathf.Min(minimumValue, maximumValue);
        float highValue = Mathf.Max(minimumValue, maximumValue);
        Keyframe[] keys = new Keyframe[keyCount];

        for (int i = 0; i < keyCount; i++)
        {
            float normalized = i / (float)(keyCount - 1);
            float time = normalized * safeDuration;
            float oscillatorValue = EvaluateOscillator(time);
            float positiveValue = Mathf.InverseLerp(-1f, 1f, oscillatorValue);
            float outputValue = Mathf.Lerp(lowValue, highValue, positiveValue);

            keys[i] = new Keyframe(time, outputValue);
        }

        Curve = new AnimationCurve(keys);
        ApplyTangents();
    }

    public float Evaluate(float time, float fallbackValue)
    {
        if (Curve == null || Curve.length == 0)
        {
            return fallbackValue;
        }

        return Curve.Evaluate(time);
    }

    private float EvaluateOscillator(float time)
    {
        float phase = cyclesPerSecond * time;

        switch (oscillatorType)
        {
            case OscillatorType.Sine:
                return Mathf.Sin(2f * Mathf.PI * phase);

            case OscillatorType.Square:
                return Mathf.Sin(2f * Mathf.PI * phase) >= 0f ? 1f : -1f;

            case OscillatorType.Saw:
                return 2f * (phase - Mathf.Floor(phase + 0.5f));

            case OscillatorType.Triangle:
                return 2f * Mathf.Abs(2f * (phase - Mathf.Floor(phase + 0.5f))) - 1f;

            case OscillatorType.Pwm:
                float cyclePosition = phase - Mathf.Floor(phase);
                return cyclePosition < Mathf.Clamp01(pulseWidth) ? 1f : -1f;

            case OscillatorType.Noise:
                return Mathf.PerlinNoise(noiseSeed, time * cyclesPerSecond) * 2f - 1f;

            default:
                return 0f;
        }
    }

    private void ApplyTangents()
    {
#if UNITY_EDITOR
        if (oscillatorType == OscillatorType.Square || oscillatorType == OscillatorType.Pwm)
        {
            for (int i = 0; i < Curve.length; i++)
            {
                AnimationUtility.SetKeyLeftTangentMode(Curve, i, AnimationUtility.TangentMode.Constant);
                AnimationUtility.SetKeyRightTangentMode(Curve, i, AnimationUtility.TangentMode.Constant);
            }

            return;
        }
#endif

        for (int i = 0; i < Curve.length; i++)
        {
            Curve.SmoothTangents(i, 0f);
        }
    }
}
